### ISSUE TITLE
How to listen print action in remote renderer

### ISSUE THREAD

**Issue by nikhilranosys** [OpenCerts/opencerts-website#460]
I have implemented remote renderer with updated structure and want to implement my own print action suggested on this link: https://github.com/OpenCerts/opencerts-website/issues/444#issuecomment-558474653

But I am not sure how to listen parent's print action in iframe.

**Comment by Nebulis** [comment]
How do you connect through the frame:
- Do you use like the example `FramedDocumentRenderer` ?(https://github.com/OpenCerts/demo-opencerts-renderer/blob/master/src/index.tsx) => in that case there is nothing to do
- Do you implement yourself the connection to the iframe ? then you need to provide a print method (same as renderDocument function)

If you are unsure, feel free to provide a link to your code so that I can help you through it

**Comment by nikhilranosys** [comment]
Here is my code repo link: https://github.com/nikhilranosys/demo-opencerts-renderer/tree/smu-templates-new

**Comment by Nebulis** [comment]
You are using `FramedDocumentRenderer`, it should work, isnt it the case ?

Could you upgrade `@govtechsg/decentralized-renderer-react-components` to latest version ? 1.2.1

**Comment by nikhilranosys** [comment]
Yes, print is working but pages are faded because of the default watermark. I want to add my own watermark thats why want to listen print action.

**Comment by Nebulis** [comment]
ok Upgrade to 1.2.1 it should fix that problem (that was the fix reason)

**Comment by nikhilranosys** [comment]
I have already upgraded to 1.2.1 but still getting same issue. It is showing gray layer in print version though I have different watermark set on my page.

**Comment by Nebulis** [comment]
How do you print, using the print button or using the shortcut (ctrl+p / cmd + p) ?

**Comment by nikhilranosys** [comment]
Using the print button.

**Comment by Nebulis** [comment]
It should work, I will try with your repository but in the meantime make sure your local version of opencerts-website is up to date as well

**Comment by Nebulis** [comment]
- Feel free to remove whatever is related to govtech (for instance govtech examples in `src/templates/govtechDemoCert`)
- Where is your custom watermark ? (which component or which css file, I cant see any watermark when printing on your branch, from storybook) I notice that you kept importing and reusing the `PrintWatermark` component which is provided by default and that you used it in some templates. if you dont need opencerts default watermark and want to use your own you should remove it

**Comment by Nebulis** [comment]
I just tried with latest opencerts-website and your branch, and didn't face the issue.

However I couldn't see your Watermark as well. I had to do the following change:

```
export const PrintWatermark: FunctionComponent = () => (
  <div
    css={css`
      width: 0;
      height: 0;
      opacity: 0;
      display: none;
      position: absolute;
      background-color: blue;
      background-repeat: repeat;
      z-index:1000;

      @media print {
        width: 100%;
        height: 100%;
        opacity: 0.6;
        display: block;
      }
    `}
    className="print-only"
  />
);
```
(adding z-index L14)

This is what I get locally
![image](https://user-images.githubusercontent.com/503185/70522005-40c80880-1b7b-11ea-95b1-72dafd75ed0f.png)
Printed from my local opencerts (latest version) using your branch and the line I added

**Comment by nikhilranosys** [comment]
Thanks for the update. Now it is working perfactly fine when I run with `npm run start`.

But when I try to export using `npm run start:static` I am getting below error:

```
[   =] Exporting (0/9)
Error occurred prerendering /collaborate: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)

Error occurred prerendering /registry: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
[  ==] Exporting (2/9)
Error occurred prerendering /privacy: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)

Error occurred prerendering /terms: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)

Error occurred prerendering /collaborators-terms: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
[ ===] Exporting (5/9)
Error occurred prerendering /faq: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)

Error occurred prerendering /404.html: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
[=   ] Exporting (7/9)
Error occurred prerendering /viewer: Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
Exporting (9/9)
Error: Export encountered errors
    at _default (D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website\node_modules\next\dist\export\index.js:14:1048)
[    ] Exporting (9/9)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencerts-website@2.0.0 export: `next export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencerts-website@2.0.0 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nikhil Gaur\AppData\Roaming\npm-cache\_logs\2019-12-10T11_46_43_850Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencerts-website@2.0.0 build:static: `next build && npm run export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencerts-website@2.0.0 build:static script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nikhil Gaur\AppData\Roaming\npm-cache\_logs\2019-12-10T11_46_43_975Z-debug.log
[2019-12-10T11_46_43_975Z-debug.log](https://github.com/OpenCerts/opencerts-website/files/3944675/2019-12-10T11_46_43_975Z-debug.log)
```

**Comment by Nebulis** [comment]
I'm not sure what's going on, There are some issues that could be related on next repo (https://github.com/zeit/next.js/issues?utf8=%E2%9C%93&q=Module+did+not+self-register)

I cant reproduce on my machine (linux)

What are you trying to achieve ? (why do you build opencerts yourself)
